### PR TITLE
Improved the UI of calculator

### PR DESCRIPTION
**Pull request by prakartigoel24**
Improved the UI of the calculator.

image

### CODE REVIEW

**Comment by prakartigoel24** [comment]
Please add hacktoberfest and hacktoberfest-accepted labels to my PR.

**Review by Neel-07 — APPROVED** [review]

**Comment by prakartigoel24** [comment]
@Neel-07 Please add hacktoberfest and hacktoberfest-accepted Labels to this.

**Comment by Neel-07** [comment]
done @prakartigoel24

**Comment by prakartigoel24** [comment]
@Neel-07 Please add the "hacktoberfest" label too. It is showing not participating.

**Pull request merged**
